name: Sync Fork

on:
  schedule:
    - cron: '0 0 * * *' # every day at midnight
  workflow_dispatch: # on button click

jobs:
  sync:

    runs-on: ubuntu-latest

    steps:
      - uses: tgymnich/fork-sync@v2.0
        with:
          token: ${{ github.token }}	
          owner: threatlabz
          repo: ransomware_notes
          base: main
          head: main
          merge_method: merge
